# Generated by Django 4.1.3 on 2023-12-07 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_tag_created_date_tag_updated_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='image',
        ),
        migrations.RemoveField(
            model_name='lesson',
            name='image',
        ),
    ]
